name: PartsUnlimited
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env:
  WEB_APP_NAME: narayanagithubwebapp
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

jobs:
  Build:
    runs-on: windows-latest
   
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Setup NuGet.exe for use with actions
      uses: NuGet/setup-nuget@v1.0.5
    
    - name: NuGet restore
      run: nuget restore ${{github.workspace}}/PartsUnlimited.sln
    
    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1
    
    - name: Publish Build artifact
      uses: actions/upload-artifact@v2
      with:
        name: drop
        path: ${{github.workspace}}/
      
  SonarCloud:
    runs-on: ubuntu-latest
    needs: [Build]
    steps:  
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@v1.3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  
  Deploy:
    name: Deploy to Azure Web App
    runs-on: windows-latest
    needs: [Build, SonarCloud]
    steps:
    - name: Download Build Artifact
      uses: actions/download-artifact@v2
      with:
        name: drop
        path: ${{github.workspace}}


    - name: Azure WebApp Deploy
      uses: Azure/webapps-deploy@v2
      with:
        app-name: ${{env.WEB_APP_NAME}}
        publish-profile: ${{secrets.WEB_APP_PUBLISH_PROFILE}}

