name: PartsUnlimited
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env:
  WEB_APP_NAME: narayanagithubwebapp
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true


jobs:
  Build:
    runs-on: windows-latest
   
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Setup NuGet.exe for use with actions
      uses: NuGet/setup-nuget@v1.0.5
    
    - name: NuGet restore
      run: nuget restore ${{github.workspace}}/PartsUnlimited.sln
    
    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1
    
    - name: Copy Selenium Tests
      uses: canastro/copy-file-action@master
      with:
        source: ${{github.workspace}}/test/PartsUnlimited.SeleniumTests/bin/Release
        target: ${{github.workspace}}/TestAssemblies'
    
    - name: Copy Database Tests
      uses: canastro/copy-file-action@master
      with:
        source: 'Database/Database'
        target: ${{github.workspace}}/Database'
    
    - name: Publish Build artifact
      uses: actions/upload-artifact@v2
      with:
        name: drop
        path: ${{github.workspace}}/
      
  
