name: PartsUnlimited
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Setup NuGet.exe for use with actions
      uses: NuGet/setup-nuget@v1.0.5
    
    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1
    
    - name: NuGet restore
      run: nuget restore ${{github.workspace}}/PartsUnlimitedSeleniumRepo/PartsUnlimited.sln
      
    - name: Publish Build artifact
      uses: actions/upload-artifact@v2
      with:
        name: drop
        path: ${{github.workspace}}/PartsUnlimitedSeleniumRepo/
        
        
        
